/**
 * types/db/complaint.ts
 *
 * TypeScript interfaces for the four complaint-lifecycle collections:
 *  - complaints         (core complaint record)
 *  - complaint_updates  (audit log of every status/assignment change)
 *  - media              (photos and files attached to a complaint)
 *  - notifications      (outbound WhatsApp and in-app messages)
 *
 * ─── Collection relationships ────────────────────────────────────────────────
 *
 *  complaints
 *    └─ citizenId        → citizens
 *    └─ organizationId   → organizations
 *    └─ constituencyId   → constituencies
 *    └─ areaId           → areas
 *    └─ wardId           → wards
 *    └─ streetId         → streets
 *    └─ categoryId       → categories
 *    └─ departmentId     → departments
 *    └─ assignedTo       → volunteers
 *    └─ assignedBy       → admins
 *
 *  complaint_updates    (subcollection-like pattern: flat collection, keyed by complaintId)
 *    └─ complaintId      → complaints
 *    └─ actorId          → admins | volunteers | "system"
 *
 *  media
 *    └─ complaintId      → complaints
 *    └─ uploadedBy       → citizens | admins | volunteers
 *
 *  notifications
 *    └─ complaintId      → complaints (nullable — some notifications are not complaint-related)
 *    └─ recipientId      → citizens | admins | volunteers
 *
 * ─── Firestore optimization notes ───────────────────────────────────────────
 *  - All foreign-key ID fields that will be used in WHERE clauses are top-level
 *    scalar fields (not nested) so Firestore indexes can be defined on them.
 *  - `constituencyId`, `wardId`, `categoryId`, `status` are all indexable this way.
 *  - `complaint_updates` is a flat collection (not a Firestore subcollection)
 *    because the dashboard needs to query "all updates by volunteer X" across
 *    multiple complaints — which subcollections cannot support.
 *  - `media` is a flat collection (not embedded in the complaint document)
 *    because documents have a 1 MiB limit and a complaint may have many photos.
 *  - `priority` is computed by the backend (category SLA + age) and stored
 *    as a sortable integer so the dashboard can ORDER BY priority DESC.
 *  - `ticketNumber` is a human-readable sequential number (not the document ID)
 *    for display in WhatsApp messages and dashboard ("CC-2024-001042").
 */

import type { Timestamp } from "firebase/firestore";
import type { DbDocument, GeoPoint } from "./master";

// ─── Shared enums / literals ─────────────────────────────────────────────────

export type ComplaintStatus =
  | "pending"       // Received, not yet assigned
  | "assigned"      // Assigned to a volunteer
  | "in_progress"   // Volunteer has started work
  | "resolved"      // Volunteer marked as done
  | "closed"        // Admin confirmed and closed
  | "reopened"      // Citizen disputed resolution
  | "rejected";     // Admin rejected (duplicate / out of scope)

export type ComplaintPriority = "low" | "medium" | "high" | "critical";

export type ComplaintSource =
  | "whatsapp"      // Filed through WhatsApp bot
  | "dashboard"     // Filed manually by an admin
  | "api";          // Filed through the REST API

// ─── complaints ───────────────────────────────────────────────────────────────
/**
 * Collection: complaints
 * Document ID: auto-generated by Firestore (addDoc).
 *
 * Core record. Every complaint filed by a citizen (via WhatsApp) or
 * created manually by an admin is one document here.
 *
 * Indexed fields for dashboard queries:
 *   constituencyId  — "show me all complaints in my constituency"
 *   wardId          — "show me complaints in ward X"
 *   categoryId      — "show me all road complaints"
 *   departmentId    — "show me BBMP complaints"
 *   status          — "show me all pending complaints"
 *   assignedTo      — "show me complaints assigned to volunteer Y"
 *   priority        — "sort by urgency"
 *   createdAt       — "sort by newest"
 *   slaDeadlineAt   — "sort by SLA breach risk"
 */
export interface Complaint extends DbDocument {
  // ── Human-readable identifier ──────────────────────────────────────────
  /**
   * Sequential human-readable ticket number.
   * Format: "CC-YYYY-NNNNNN"  e.g. "CC-2024-001042"
   * Generated by the backend; never the Firestore document ID.
   */
  ticketNumber: string;

  // ── Origin ─────────────────────────────────────────────────────────────
  source: ComplaintSource;
  /** WhatsApp message ID from the Meta Cloud API. Null for dashboard-created complaints. */
  whatsappMessageId: string | null;

  // ── Citizen ────────────────────────────────────────────────────────────
  /** Document ID of the citizen (E.164 phone without "+"). */
  citizenId: string;
  /** Stored redundantly for display without a join. */
  citizenPhone: string;
  /** Citizen display name at time of filing. */
  citizenName: string | null;

  // ── Location (all stored as IDs) ────────────────────────────────────────
  organizationId: string;
  constituencyId: string;
  areaId: string | null;
  wardId: string | null;
  streetId: string | null;
  /**
   * Raw GPS coordinates from the citizen's device.
   * Stored in addition to the ID-based location for map display.
   */
  geoLocation: GeoPoint | null;
  /** Human-readable address resolved from GPS (reverse geocoding). */
  geoAddress: string | null;

  // ── Classification ──────────────────────────────────────────────────────
  categoryId: string;
  departmentId: string | null;

  // ── Content ─────────────────────────────────────────────────────────────
  description: string;
  /**
   * IDs of media documents attached to this complaint.
   * Stored as an array here for O(1) "does this complaint have photos?" check.
   * Full metadata is in the media collection.
   */
  mediaIds: string[];

  // ── Workflow ─────────────────────────────────────────────────────────────
  status: ComplaintStatus;
  priority: ComplaintPriority;
  /**
   * Priority as a sortable integer for ORDER BY.
   * critical=4, high=3, medium=2, low=1
   */
  priorityScore: number;
  /** Volunteer UID this complaint is assigned to. */
  assignedTo: string | null;
  /** Admin UID who made the assignment. */
  assignedBy: string | null;
  assignedAt: Timestamp | null;

  // ── SLA ──────────────────────────────────────────────────────────────────
  /**
   * Deadline computed from category.defaultSlaHours at creation time.
   * Stored so the dashboard can query "WHERE slaDeadlineAt < now()" efficiently.
   */
  slaDeadlineAt: Timestamp | null;
  /** True if the SLA was breached (set by a scheduled backend job). */
  slaBreached: boolean;

  // ── Resolution ────────────────────────────────────────────────────────────
  /** Admin or volunteer resolution note. */
  resolutionNote: string | null;
  resolvedAt: Timestamp | null;
  closedAt: Timestamp | null;
  /** Star rating given by the citizen (1-5). Null until rated. */
  citizenRating: number | null;
  citizenFeedback: string | null;

  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// ─── complaint_updates ────────────────────────────────────────────────────────
/**
 * Collection: complaint_updates
 * Document ID: auto-generated.
 *
 * Immutable audit log. One document per state change or action on a complaint.
 * Never updated — only appended.
 *
 * Indexed fields:
 *   complaintId — "show me all updates for complaint X"
 *   actorId     — "show me all actions taken by volunteer Y"
 *   createdAt   — sort chronologically
 */
export type UpdateAction =
  | "created"
  | "assigned"
  | "unassigned"
  | "status_changed"
  | "priority_changed"
  | "note_added"
  | "media_added"
  | "rated"
  | "reopened"
  | "rejected"
  | "closed"
  | "sla_breached";

export interface ComplaintUpdate extends DbDocument {
  complaintId: string;
  /**
   * UID of the admin or volunteer who triggered this update.
   * "system" for automated actions (SLA breach, scheduled jobs).
   */
  actorId: string;
  /** Human-readable name of the actor (denormalized for display). */
  actorName: string;
  action: UpdateAction;
  /** Status the complaint moved FROM. */
  fromStatus: ComplaintStatus | null;
  /** Status the complaint moved TO. */
  toStatus: ComplaintStatus | null;
  /** Volunteer UID assigned (for "assigned" action). */
  assignedTo: string | null;
  /** Free-text note visible to the citizen in WhatsApp updates. */
  note: string | null;
  /** Whether this update was sent to the citizen via WhatsApp. */
  notifiedCitizen: boolean;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// ─── media ────────────────────────────────────────────────────────────────────
/**
 * Collection: media
 * Document ID: auto-generated.
 *
 * One document per uploaded file. Separated from the complaint document
 * to avoid the 1 MiB document size limit and to allow media-specific queries.
 *
 * Indexed fields:
 *   complaintId  — "get all photos for complaint X"
 *   uploadedBy   — "get all files uploaded by citizen Y"
 */
export type MediaType = "image" | "video" | "document" | "audio";
export type MediaStatus = "pending" | "uploaded" | "failed" | "deleted";
export type MediaUploadedBy = "citizen" | "volunteer" | "admin";

export interface Media extends DbDocument {
  complaintId: string;
  /** UID or citizenId of the uploader. */
  uploadedById: string;
  uploadedByType: MediaUploadedBy;
  type: MediaType;
  /** MIME type. e.g. "image/jpeg" */
  mimeType: string;
  /** Original file name. e.g. "photo_from_whatsapp.jpg" */
  originalFileName: string;
  /** Full Firebase Storage path. e.g. "complaints/abc123/photos/1720000000000-photo.jpg" */
  storagePath: string;
  /** Public download URL from Firebase Storage. */
  downloadUrl: string;
  /** File size in bytes. */
  sizeBytes: number;
  status: MediaStatus;
  /** WhatsApp media ID (for files received from the Meta Cloud API). */
  whatsappMediaId: string | null;
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// ─── notifications ────────────────────────────────────────────────────────────
/**
 * Collection: notifications
 * Document ID: auto-generated.
 *
 * One document per outbound notification attempt.
 * Covers both WhatsApp messages (to citizens) and in-app notifications
 * (to admins/volunteers on the dashboard).
 *
 * Indexed fields:
 *   recipientId  — "show me all notifications for user X"
 *   complaintId  — "show me all notifications sent for complaint Y"
 *   status       — retry jobs query WHERE status = "pending" or "failed"
 *   channel      — filter by delivery channel
 *   createdAt    — sort for notification feed
 */
export type NotificationChannel = "whatsapp" | "in_app" | "email";
export type NotificationStatus = "pending" | "sent" | "delivered" | "read" | "failed";
export type NotificationRecipientType = "citizen" | "admin" | "volunteer";

/**
 * WhatsApp template message parameters.
 * Stored so failed messages can be retried without rebuilding the payload.
 */
export interface WhatsAppTemplatePayload {
  templateName: string;
  languageCode: string;
  /** Ordered list of variable substitutions for the template. */
  parameters: string[];
}

export interface Notification extends DbDocument {
  /** ID of the recipient. citizenId for citizens; UID for admins/volunteers. */
  recipientId: string;
  recipientType: NotificationRecipientType;
  channel: NotificationChannel;

  // ── Content ──────────────────────────────────────────────────────────────
  title: string;
  body: string;
  /**
   * Structured WhatsApp template payload.
   * Null for in-app and email notifications.
   */
  whatsAppPayload: WhatsAppTemplatePayload | null;

  // ── Association ───────────────────────────────────────────────────────────
  /** The complaint this notification is about. Null for non-complaint messages. */
  complaintId: string | null;
  /** Human-readable ticket number for the notification body. */
  ticketNumber: string | null;

  // ── Delivery ──────────────────────────────────────────────────────────────
  status: NotificationStatus;
  /** WhatsApp message ID returned by the Meta Cloud API on success. */
  externalMessageId: string | null;
  /** Error message if status is "failed". */
  errorMessage: string | null;
  /** Number of send attempts (for retry backoff logic). */
  attemptCount: number;
  sentAt: Timestamp | null;
  deliveredAt: Timestamp | null;
  readAt: Timestamp | null;

  createdAt: Timestamp;
  updatedAt: Timestamp;
}
